import {
  TimeframeFilter,
  KpiItem,
  PaymentBreakdownItem,
  TopProductItem,
  LowStockAlertItem,
  RecentTransactionItem,
} from '../interface/dashboard';

export const THEME_COLORS = {
  primary: '#7B468C',
  primaryDark: '#5E326C',
  primaryLight: '#F3EBF7',
  primaryBorder: '#E7D5EE',
  accentPurple: '#9A6AB2',
  bgLight: '#F8FAFC',
  cardBg: '#FFFFFF',
  textPrimary: '#1E293B',
  textSecondary: '#64748B',
  textMuted: '#94A3B8',
  borderColor: '#E2E8F0',
  success: '#10B981',
  successBg: '#ECFDF5',
  warning: '#F59E0B',
  warningBg: '#FFFBEB',
  danger: '#EF4444',
  dangerBg: '#FEF2F2',
  info: '#3B82F6',
  infoBg: '#EFF6FF',
};

export const TIMEFRAME_OPTIONS: TimeframeFilter[] = [
  'Today',
  'Yesterday',
  'This Week',
  'This Month',
];

export const INITIAL_KPI_DATA: Record<TimeframeFilter, KpiItem[]> = {
  Today: [
    {
      id: 'revenue',
      title: 'Total Revenue',
      value: 'Rs. 245,850',
      subtext: 'vs yesterday',
      changePercent: '+14.2%',
      isPositive: true,
      iconName: 'dollar',
      accentColor: '#7B468C',
      bgTint: '#F3EBF7',
    },
    {
      id: 'orders',
      title: 'Total Sales Count',
      value: '356 Orders',
      subtext: 'vs yesterday',
      changePercent: '+8.5%',
      isPositive: true,
      iconName: 'shopping-cart',
      accentColor: '#3B82F6',
      bgTint: '#EFF6FF',
    },
    {
      id: 'profit',
      title: 'Net Profit (Est.)',
      value: 'Rs. 86,050',
      subtext: '35.0% profit margin',
      changePercent: '+11.8%',
      isPositive: true,
      iconName: 'trending-up',
      accentColor: '#10B981',
      bgTint: '#ECFDF5',
    },
    {
      id: 'lowStock',
      title: 'Low Stock Items',
      value: '12 Items',
      subtext: '4 critical alerts',
      changePercent: '-3 items',
      isPositive: false,
      iconName: 'alert-triangle',
      accentColor: '#EF4444',
      bgTint: '#FEF2F2',
    },
  ],
  Yesterday: [
    {
      id: 'revenue',
      title: 'Total Revenue',
      value: 'Rs. 215,200',
      subtext: 'previous day',
      changePercent: '+5.1%',
      isPositive: true,
      iconName: 'dollar',
      accentColor: '#7B468C',
      bgTint: '#F3EBF7',
    },
    {
      id: 'orders',
      title: 'Total Sales Count',
      value: '328 Orders',
      subtext: 'previous day',
      changePercent: '+2.4%',
      isPositive: true,
      iconName: 'shopping-cart',
      accentColor: '#3B82F6',
      bgTint: '#EFF6FF',
    },
    {
      id: 'profit',
      title: 'Net Profit (Est.)',
      value: 'Rs. 75,320',
      subtext: '35.0% profit margin',
      changePercent: '+4.0%',
      isPositive: true,
      iconName: 'trending-up',
      accentColor: '#10B981',
      bgTint: '#ECFDF5',
    },
    {
      id: 'lowStock',
      title: 'Low Stock Items',
      value: '15 Items',
      subtext: '5 critical alerts',
      changePercent: '+2 items',
      isPositive: false,
      iconName: 'alert-triangle',
      accentColor: '#EF4444',
      bgTint: '#FEF2F2',
    },
  ],
  'This Week': [
    {
      id: 'revenue',
      title: 'Total Revenue',
      value: 'Rs. 1,480,500',
      subtext: 'vs last week',
      changePercent: '+18.4%',
      isPositive: true,
      iconName: 'dollar',
      accentColor: '#7B468C',
      bgTint: '#F3EBF7',
    },
    {
      id: 'orders',
      title: 'Total Sales Count',
      value: '2,140 Orders',
      subtext: 'vs last week',
      changePercent: '+12.1%',
      isPositive: true,
      iconName: 'shopping-cart',
      accentColor: '#3B82F6',
      bgTint: '#EFF6FF',
    },
    {
      id: 'profit',
      title: 'Net Profit (Est.)',
      value: 'Rs. 518,175',
      subtext: '35.0% profit margin',
      changePercent: '+16.5%',
      isPositive: true,
      iconName: 'trending-up',
      accentColor: '#10B981',
      bgTint: '#ECFDF5',
    },
    {
      id: 'lowStock',
      title: 'Low Stock Items',
      value: '12 Items',
      subtext: '4 critical alerts',
      changePercent: '-5 items',
      isPositive: false,
      iconName: 'alert-triangle',
      accentColor: '#EF4444',
      bgTint: '#FEF2F2',
    },
  ],
  'This Month': [
    {
      id: 'revenue',
      title: 'Total Revenue',
      value: 'Rs. 5,920,000',
      subtext: 'vs last month',
      changePercent: '+22.0%',
      isPositive: true,
      iconName: 'dollar',
      accentColor: '#7B468C',
      bgTint: '#F3EBF7',
    },
    {
      id: 'orders',
      title: 'Total Sales Count',
      value: '8,540 Orders',
      subtext: 'vs last month',
      changePercent: '+15.3%',
      isPositive: true,
      iconName: 'shopping-cart',
      accentColor: '#3B82F6',
      bgTint: '#EFF6FF',
    },
    {
      id: 'profit',
      title: 'Net Profit (Est.)',
      value: 'Rs. 2,072,000',
      subtext: '35.0% profit margin',
      changePercent: '+20.1%',
      isPositive: true,
      iconName: 'trending-up',
      accentColor: '#10B981',
      bgTint: '#ECFDF5',
    },
    {
      id: 'lowStock',
      title: 'Low Stock Items',
      value: '12 Items',
      subtext: '4 critical alerts',
      changePercent: 'stable',
      isPositive: false,
      iconName: 'alert-triangle',
      accentColor: '#EF4444',
      bgTint: '#FEF2F2',
    },
  ],
};

export const CHART_DATA_BY_TIMEFRAME = {
  Today: {
    labels: ['8 AM', '10 AM', '12 PM', '2 PM', '4 PM', '6 PM', '8 PM'],
    revenue: [18500, 32400, 45100, 68900, 42000, 25800, 13150],
    orders: [25, 48, 62, 95, 58, 42, 26],
    peakPeriod: '2:00 PM - 4:00 PM',
    avgTicket: 'Rs. 690',
    topHourRevenue: 'Rs. 68,900',
  },
  Yesterday: {
    labels: ['8 AM', '10 AM', '12 PM', '2 PM', '4 PM', '6 PM', '8 PM'],
    revenue: [15200, 28900, 41200, 58400, 39500, 21800, 10200],
    orders: [22, 42, 56, 84, 52, 38, 20],
    peakPeriod: '2:00 PM - 4:00 PM',
    avgTicket: 'Rs. 656',
    topHourRevenue: 'Rs. 58,400',
  },
  'This Week': {
    labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    revenue: [185000, 210000, 195000, 245850, 230000, 275000, 139650],
    orders: [270, 310, 285, 356, 335, 390, 194],
    peakPeriod: 'Saturday Peak',
    avgTicket: 'Rs. 691',
    topHourRevenue: 'Rs. 275,000',
  },
  'This Month': {
    labels: ['W1', 'W2', 'W3', 'W4'],
    revenue: [1350000, 1420000, 1650000, 1500000],
    orders: [1950, 2050, 2380, 2160],
    peakPeriod: 'Week 3 Peak',
    avgTicket: 'Rs. 693',
    topHourRevenue: 'Rs. 1,650,000',
  },
};

export const PAYMENT_BREAKDOWN_DATA: PaymentBreakdownItem[] = [
  {
    method: 'Cash',
    amount: 110632,
    formattedAmount: 'Rs. 110,632',
    percentage: 45,
    count: 160,
    color: '#7B468C',
  },
  {
    method: 'Card',
    amount: 86047,
    formattedAmount: 'Rs. 86,047',
    percentage: 35,
    count: 125,
    color: '#4F46E5',
  },
  {
    method: 'QR',
    amount: 36877,
    formattedAmount: 'Rs. 36,877',
    percentage: 15,
    count: 53,
    color: '#10B981',
  },
  {
    method: 'Online',
    amount: 12294,
    formattedAmount: 'Rs. 12,294',
    percentage: 5,
    count: 18,
    color: '#F59E0B',
  },
];

export const TOP_PRODUCTS_DATA: TopProductItem[] = [
  {
    id: '1',
    name: 'Coca Cola 500ml',
    category: 'Beverages',
    soldUnits: 245,
    revenue: 'Rs. 36,750',
    stockLeft: 42,
    trend: '+18%',
  },
  {
    id: '2',
    name: 'Araliya White Rice 5Kg',
    category: 'Grocery',
    soldUnits: 180,
    revenue: 'Rs. 252,000',
    stockLeft: 14,
    trend: '+12%',
  },
  {
    id: '3',
    name: 'Anchor Milk Powder 400g',
    category: 'Dairy',
    soldUnits: 120,
    revenue: 'Rs. 138,000',
    stockLeft: 8,
    trend: '+9%',
  },
  {
    id: '4',
    name: 'Munchee Super Cream Cracker',
    category: 'Biscuits & Snacks',
    soldUnits: 98,
    revenue: 'Rs. 24,500',
    stockLeft: 65,
    trend: '+5%',
  },
];

export const LOW_STOCK_ALERTS_DATA: LowStockAlertItem[] = [
  {
    id: 'ls1',
    name: 'Araliya White Rice 5Kg',
    sku: 'SKU-RICE-001',
    stockLeft: 3,
    minThreshold: 10,
    category: 'Grocery',
    urgency: 'critical',
  },
  {
    id: 'ls2',
    name: 'Refined White Sugar 1Kg',
    sku: 'SKU-SUG-002',
    stockLeft: 5,
    minThreshold: 15,
    category: 'Grocery',
    urgency: 'critical',
  },
  {
    id: 'ls3',
    name: 'Anchor Milk Powder 400g',
    sku: 'SKU-MILK-004',
    stockLeft: 8,
    minThreshold: 20,
    category: 'Dairy',
    urgency: 'warning',
  },
  {
    id: 'ls4',
    name: 'Dilmah Ceylon Tea 100g',
    sku: 'SKU-TEA-009',
    stockLeft: 9,
    minThreshold: 15,
    category: 'Beverages',
    urgency: 'warning',
  },
];

export const RECENT_TRANSACTIONS_DATA: RecentTransactionItem[] = [
  {
    id: 't1',
    invoiceNo: 'INV-2026-0842',
    customerName: 'Walk-in Customer',
    timeAgo: '2 mins ago',
    itemSummary: 'Burger x2, Iced Tea x1',
    paymentMethod: 'Cash',
    amount: 'Rs. 1,550',
    status: 'Completed',
  },
  {
    id: 't2',
    invoiceNo: 'INV-2026-0841',
    customerName: 'Kamal Perera',
    timeAgo: '14 mins ago',
    itemSummary: 'Rice 5Kg x1, Milk Powder x2',
    paymentMethod: 'Card',
    amount: 'Rs. 4,160',
    status: 'Completed',
  },
  {
    id: 't3',
    invoiceNo: 'INV-2026-0840',
    customerName: 'Walk-in Customer',
    timeAgo: '28 mins ago',
    itemSummary: 'Pizza Family Combo x1',
    paymentMethod: 'QR',
    amount: 'Rs. 3,450',
    status: 'Completed',
  },
  {
    id: 't4',
    invoiceNo: 'INV-2026-0839',
    customerName: 'Saman Silva',
    timeAgo: '45 mins ago',
    itemSummary: 'Biscuits x3, Soft Drink 1.5L',
    paymentMethod: 'Cash',
    amount: 'Rs. 890',
    status: 'Completed',
  },
];
