import { InventoryItem, InventoryCategory } from '../interface/inventory';

export const INVENTORY_CATEGORIES: InventoryCategory[] = [
  'All',
  'Groceries',
  'Beverages',
  'Dairy',
  'Bakery',
  'Snacks',
  'Household',
];

export const INITIAL_INVENTORY_DATA: InventoryItem[] = [
  {
    id: 1,
    name: 'Samba Rice 5Kg',
    quantity: 25,
    unit: 'kg',
    price: 1450,
    costPrice: 1200,
    category: 'Groceries',
    sku: 'SKU-RICE-01',
    minStockLevel: 5,
  },
  {
    id: 2,
    name: 'Fresh Milk 1L',
    quantity: 12,
    unit: 'l',
    price: 480,
    costPrice: 400,
    category: 'Dairy',
    sku: 'SKU-MILK-02',
    minStockLevel: 15,
  },
  {
    id: 3,
    name: 'Coca Cola 500ml',
    quantity: 48,
    unit: 'pc',
    price: 180,
    costPrice: 140,
    category: 'Beverages',
    sku: 'SKU-BEV-03',
    minStockLevel: 10,
  },
  {
    id: 4,
    name: 'Ceylon Tea Bags 100s',
    quantity: 4,
    unit: 'pc',
    price: 950,
    costPrice: 780,
    category: 'Beverages',
    sku: 'SKU-TEA-04',
    minStockLevel: 5,
  },
  {
    id: 5,
    name: 'White Sugar 1Kg',
    quantity: 0,
    unit: 'kg',
    price: 280,
    costPrice: 230,
    category: 'Groceries',
    sku: 'SKU-SUG-05',
    minStockLevel: 10,
  },
  {
    id: 6,
    name: 'Chocolate Cake Slice',
    quantity: 15,
    unit: 'pc',
    price: 450,
    costPrice: 320,
    category: 'Bakery',
    sku: 'SKU-BAK-06',
    minStockLevel: 5,
  },
  {
    id: 7,
    name: 'Dishwash Liquid 500ml',
    quantity: 8,
    unit: 'pc',
    price: 420,
    costPrice: 330,
    category: 'Household',
    sku: 'SKU-HOU-07',
    minStockLevel: 3,
  },
];
